version: '3'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - PORT=8000
      - DATABASE_URL=mongodb://db

  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
